name: My Scheduled Script

on:
  schedule:
    # Расписание в формате POSIX cron
    # Этот пример запускает скрипт каждые 6 часов
    - cron: '*/5 7-23 * * *'
  workflow_dispatch: # Позволяет запускать скрипт вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python # Или Node.js, если скрипт на нем
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements.txt"

      - name: Run script
        run: python my_script.py
